apiVersion: v1
kind: ConfigMap
metadata:
  name: word-picker-options-c
  namespace: word-picker-bc-al
data:
  custom_options.txt: |
    ciprus
    cica

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-picker-c
  namespace: word-picker-bc-al
spec:
  replicas: 2
  selector:
    matchLabels:
      app: word-picker
      letter: c
  template:
    metadata:
      labels:
        app: word-picker
        letter: c
    spec:
      containers:
      - name: word-picker
        image: tinmancoding/word-picker:v2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: options-config-map
          mountPath: /code/config
        env:
        - name: OPTIONS_FILE
          value: /code/config/custom_options.txt
      volumes:
      - name: options-config-map
        configMap:
          name: word-picker-options-c
